package com.junikarp.qbank.mock;

import com.junikarp.qbank.question.domain.Question;
import com.junikarp.qbank.question.service.port.QuestionRepository;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

public class FakeQuestionRepository implements QuestionRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Question> data = Collections.synchronizedList(new ArrayList<>());
    private final List<Bookmark> bookmarkData = Collections.synchronizedList(new ArrayList<>());
    private record Bookmark(Long userId, Long questionId) {}

    public void addBookmark(Long userId, Long questionId) {
        bookmarkData.add(new Bookmark(userId, questionId));
    }

    @Override
    public Question save(Question question) {
        if (question.getId() == null || question.getId() == 0) {
            Question newQuestion = Question.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .question(question.getQuestion())
                    .explanation(question.getExplanation())
                    .choices(question.getChoices())
                    .build();
            data.add(newQuestion);
            return newQuestion;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), question.getId()));
            data.add(question);
            return question;
        }
    }

    @Override
    public List<Question> findAll() {
        return data;
    }

    @Override
    public List<Question> findBookmarkedQuestionsByUserId(Long userId) {
        List<Long> questionIdList = bookmarkData.stream()
                .filter(bookmark -> bookmark.userId.equals(userId))
                .map(Bookmark::questionId)
                .toList();
        return data.stream()
                .filter(question -> questionIdList.contains(question.getId()))
                .collect(Collectors.toList());
    }

}
