package com.junikarp.qbank.question.mock;

import com.junikarp.qbank.question.domain.Question;
import com.junikarp.qbank.question.service.port.QuestionRepository;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public class FakeQuestionRepository implements QuestionRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Question> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Question save(Question question) {
        if (question.getId() == null || question.getId() == 0) {
            Question newQuestion = Question.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .question(question.getQuestion())
                    .explanation(question.getExplanation())
                    .options(question.getOptions())
                    .build();
            data.add(newQuestion);
            return newQuestion;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), question.getId()));
            data.add(question);
            return question;
        }
    }

    @Override
    public List<Question> findAll() {
        return data;
    }

}
